openapi: 3.0.3
info:
  title: Metatavu Home lambdas
  description: Metatavu Home lambdas
  version: 1.0.0

security:
  - bearerAuth: []

paths:
  "/allocations":
    get:
      operationId: listAllocations
      summary: Lists Forecast allocations
      description: |
        Lists Forecast allocations
      tags:
        - Allocations
      parameters:
        - name: startDate
          required: false
          in: query
          description: Start date range
          schema:
            type: string
        - name: endDate
          required: false
          in: query
          description: End date range
          schema:
            type: string
        - name: personId
          required: false
          in: query
          description: Search by person Id
          schema:
            type: string
        - name: projectId
          required: false
          in: query
          description: Search by project Id
          schema:
            type: string
      responses:
        "200":
          description: A list of Forecast allocations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Allocations"

  "/projects":
    get:
      operationId: listProjects
      summary: Lists Forecast projects
      description: |
        Lists Running Forecast projects
      tags:
        - Projects
      parameters:
        - name: startDate
          required: false
          in: query
          description: Start date range
          schema:
            type: string
        - name: endDate
          required: false
          in: query
          description: End date range
          schema:
            type: string
        - name: projectId
          required: false
          in: query
          description: Search by project Id
          schema:
            type: string
      responses:
        "200":
          description: A list of Running Forecast projects
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Projects"

  "/tasks":
    get:
      operationId: listProjectTasks
      summary: Lists Forecast project tasks
      description: |
        Lists Forecast project tasks
      tags:
        - Tasks
      parameters:
        - name: projectId
          required: true
          in: query
          description: Forecast project id
          schema:
            type: integer
      responses:
        "200":
          description: A list of Forecast project tasks
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tasks"

  "/time-entries":
    get:
      operationId: listProjectTasks
      summary: Lists Forecast project time entries
      description: |
        Lists Forecast project time entries
      tags:
        - Time entries
      parameters:
        - name: projectId
          required: true
          in: query
          description: Forecast project id
          schema:
            type: integer
      responses:
        "200":
          description: A list of Forecast project tasks
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Time-entries"

  "/salesLeads":
    get:
      operationId: listSalesLeads
      summary: Lists all Leads from Pipedrive
      description: |
        Lists Leads from Pipedrive
      tags:
        - Leads
      responses:
        "200":
          description: Lists Leads from Pipedrive
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Lead"

  "/salesDeals/{status}":
    get:
      operationId: listSalesDeals
      summary: Lists all Deals from Pipedrive
      description: |
        Lists open Deals from Pipedrive
      tags:
        - Deals
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: string  
          description: Pipedrive Deal status    
      responses:
        "200":
          description: Lists Deals from Pipedrive
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Deal"

  "/getLeadById/{leadId}":
    get:
      operationId: getLeadById
      summary: List lead data by id from Pipedrive 
      tags:
        - LeadById
      description: |
        Get more data of a lead by id from Pipedrive
      parameters:
        - name: leadId
          in: path
          required: true
          schema:
            type: string
          description: Lead Id used to identify a pipedrive lead
      responses:
        "200":
          description: Successful operation
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Lead"

  "/getDealById/{dealId}":
    get:
      operationId: getDealById
      summary: List deal data by id from Pipedrive 
      tags:
        - DealById
      description: |
        Get more data of a deal by id from Pipedrive
      parameters:
        - name: dealId
          in: path
          required: true
          schema:
            type: integer
          description: Deal Id used to identify a pipedrive deal
      responses:
        "200":
          description: Successful operation
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Deal"

  "/addDealInterest/{dealId}":
    put:
      summary: Add interest to a Pipedrive deal
      description: |
        Updates string where deal interests are stored in Pipedrive
      tags:
        - Interest
      parameters:
        - name: dealId
          in: path
          required: true
          schema:
            type: integer
          description: Deal Id used to identify a deal where the interest is updated
      responses:
        "200":
          description: Successful operation
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Interest"

  "/addLeadInterest/{leadId}":
    patch:
      summary: Add interest to a Pipedrive lead
      description: |
        Updates string where lead interests are stored in Pipedrive
      tags:
        - Interest
      parameters:
        - name: leadId
          in: path
          required: true
          schema:
            type: string
          description: LeadId used to identify a lead where the interest is updated
      responses:
        "200":
          description: Successful operation
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Interest"

  "/removeDealInterest/{dealId}":
    put:
      summary: Remove interest to a Pipedrive deal
      description: |
        Updates string where intrests are stored in Pipedrive
      tags:
        - Interest
      parameters:
        - name: dealId
          in: path
          required: true
          schema:
            type: integer
          description: Deal Id used to identify a deal where the interest is updated
      responses:
        "200":
          description: Successful operation
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Interest"

  "/removeLeadInterest/{leadId}":
    patch:
      summary: Remove interest to a Pipedrive lead
      description: |
        Updates string where intrests are stored in Pipedrive
      tags:
        - Interest
      parameters:
        - name: leadId
          in: path
          required: true
          schema:
            type: string
          description: LeadId used to identify a lead where the interest is updated
      responses:
        "200":
          description: Successful operation
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Interest"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Allocations:
      type: object
      description: Allocation data from Forecast Api
      properties:
        id:
          type: integer
        project:
          type: integer
        person:
          type: integer
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        monday:
          type: integer
        tuesday:
          type: integer
        wednesday:
          type: integer
        thursday:
          type: integer
        friday:
          type: integer
        notes:
          type: string

    Projects:
      type: object
      description: Project data from Forecast API
      properties:
        id:
          type: integer
        name:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        status:
          type: string
        stage:
          type: string

    Tasks:
      type: object
      description: Project task data from Forecast API
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        projectId:
          type: integer
        remaining:
          type: integer
        estimate:
          type: integer
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        highPriority:
          type: boolean
        assignedPersons:
          type: array
          items:
            type: integer

    Time-entries:
      type: object
      description: Project data time entries from Forecast API
      properties:
        id:
          type: integer
        person:
          type: integer
        project:
          type: integer
        task: 
          type: integer
        timeRegistered:
          type: integer

    Lead:
      type: object
      description: Lead data from Pipedrive API
      required:
        - leadId
        - title
        - interested
        - usedTech
        - addTime
        - updateTime
        - nextActivityDate
        - labelIds
      properties:
        leadId:
          type: string
          format: uuid
          description: LeadId is used to identify projects
        title:
          type: string
          description: Title or a Name of a Lead
        interested:
          type: string
          description: String where userIds are stored separated with semicolon.
        usedTech:
          type: string
          description: String where usedTech are stored separated with semicolon.
        addTime:
          type: string
          format: date-time
          description: Time when Lead is created or added to Pipedrive
        updateTime:
          type: string
          format: date-time
          description: Time when Lead is last updated to Pipedrive
        nextActivityDate:
          type: string
          format: date-time
          description: Time when next activity is going to happen on a Lead
        labelIds:
          type: array
          items:
            type: string
          description: String array where Lead labels are stored. labelIds are 'Hot', 'Warm' or 'Cold'

    Deal:
      type: object
      description: Deal data from Pipedrive API
      required:
        - dealId
        - title
        - interested
        - usedTech
        - value
        - currency
        - addTime
        - updateTime
        - nextActivityDate
        - nextActivitySubject
        - nextActivityNote
        - status
      properties:
        dealId:
          type: integer
          description: DealId is used to identify projects
        title:
          type: string
          description: Title or a Name of a Deal
        interested:
          type: string
          description: String where userIds are stored separated with semicolon.
        usedTech:
          type: string
          description: String where usedTech are stored separated with semicolon.
        value:
          type: number
          description: Value of a deal
        currency:
          type: string
          description: Currency that is used to tell the value of a deal
        addTime:
          type: string
          format: date-time
          description: Time when Deal is created or added to Pipedrive
        updateTime:
          type: string
          format: date-time
          description: Time when Deal is last updated to Pipedrive
        nextActivityDate:
          type: string
          format: date-time
          description: Time when next activity is going to happen on a Deal
        nextActivitySubject:
          type: string
          description: Used to tell the subject of a next activity. 
        nextActivityNote:
          type: string
          description: Holds more information about the next activity. 
        status:
          type: string
          description: Status of a Deal. Is the deal open, lost or won

    Interest:
      type: object
      description: Adding or removing interest to Pipedrive API
      required:
        - interest
      properties:
        interest:
          type: string
          description: String where userIds are stored separated with semicolon.
